name: Laravel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Stap 1: Haal de code van de repository op
    - uses: actions/checkout@v3

    # Stap 2: Stel PHP in
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, sqlite

    # Stap 3: Installeer de Composer afhankelijkheden
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    # Stap 4: Application Key genereren
    - name: Generate Application Key
      run: php artisan key:generate

    # Stap 5: Cache configuratie
    - name: Cache Configuration
      run: php artisan config:cache

    # Stap 6: Database migraties uitvoeren
    - name: Run Migrations
      run: php artisan migrate --database=sqlite --force

    # Stap 7: Voer de tests uit
    - name: Run TaskTest
      run: ./vendor/bin/phpunit tests/Feature/TaskTest.php
